# Generated by Django 4.0.6 on 2022-07-23 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('middle_name', models.CharField(default=None, max_length=20, verbose_name='Отчество')),
                ('email_adress', models.CharField(max_length=50, verbose_name='Электронная почта')),
                ('telephone_number', models.CharField(max_length=11, verbose_name='Телефон')),
                ('password', models.TextField(verbose_name='Пароль')),
                ('user_status', models.CharField(choices=[('delete', 'delete'), ('active', 'active')], max_length=10, verbose_name='Статус клиента')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма заказа')),
                ('direct_transaction', models.CharField(choices=[('In', 'In'), ('Out', 'Out')], max_length=5, verbose_name='Направление транзакции')),
                ('status_transaction', models.CharField(choices=[('confirm', 'confirm'), ('noconfirm', 'noconfirm')], max_length=12, verbose_name='Статус транзакции')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client', verbose_name='Идентификационный номер клиента')),
            ],
        ),
    ]
