# Generated by Django 4.0.6 on 2022-07-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_transaction_summa_transaction_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20, null=True, verbose_name='Изменение имени')),
                ('surname', models.CharField(default=None, max_length=20, null=True, verbose_name='Изменение фамилии')),
                ('middle_name', models.CharField(default=None, max_length=20, null=True, verbose_name='Изменение отчества')),
                ('email_adress', models.EmailField(default=None, max_length=254, null=True, verbose_name='Изменение электронной почты')),
                ('telephone_number', models.CharField(default=None, max_length=12, null=True, verbose_name='Изменение телефона')),
                ('password', models.TextField(default=None, null=True, verbose_name='Изменение пароля')),
                ('user_status', models.CharField(default=None, max_length=10, null=True, verbose_name='Изменение статуса клиента')),
            ],
        ),
    ]
